### ISSUE TITLE
Can you share source codes ?

### ISSUE THREAD

**Issue by Furkan125** [daniel-tran/merio-reborn#4]

**Comment by daniel-tran** [comment]
As quoted from the `README.md` file:

> Q. Will the source code ever be uploaded?
>
>A. Not really. Because "MERIO Reborn" is a sequel from the first game, it builds on the initial source code which was developed by someone else. I would have to get in touch with said person for confirmation that some of their code will be publicly available...

Probably the best thing I can do is just provide code snippets (the ones that I personally wrote for this project) for particular in-game functionalities that you're interested in - assuming you've played the game.
